### ISSUE TITLE
Rust compiler is outdated

### ISSUE THREAD

**Issue by vks** [mattgodbolt/gcc-explorer#100]
The currently nightly seems to be completely broken on http://rust.godbolt.org, and the most recent available stable is 1.1, while 1.7 is soon to be released.

**Comment by mattgodbolt** [comment]
Good point! Will do some updating!

**Comment by mattgodbolt** [comment]
Live site now has working nightly, beta and Rusts 1.0 through 1.7.  Thanks for the report!

**Comment by vks** [comment]
Thanks for the quick update!
