### ISSUE TITLE
dummy main doesn't compile with -xc, making binary mode less convenient

### ISSUE THREAD

**Issue by pcordes** [mattgodbolt/gcc-explorer#106]
http://goo.gl/OoSBgd:

The default is to compile as C++, but that sometimes results in different asm output, even for code that's legal in C and C++.  Fortunately, it's possible to override with -xc, to get g++ to compile as C.  I often use that even when I'm not using C99 variable-length arrays or whatever other C-only feature.

```
/tmp/gcc-explorer-compiler116213-74-hgj2d1/example.cpp: In function 'main':
2 : error: parameter name omitted
int main(int,char**){/*stub provided by Compiler Explorer*/}
^
2 : error: parameter name omitted
Compilation failed
```

I usually type `int main(){}` into my source as a workaround, but I'd suggest using:

```int main(int argc, char**argv){/*stub*/}```

to be properly correct for all future cases.  (IIRC, the C and C++ standards specify an implicit `return 0` if main doesn't have an explicit return, which is why these stubs don't generate warnings.)

**Comment by mattgodbolt** [comment]
Thanks for the report! I hadn't named them before as otherwise with warnings on one gets "unused variables". Will fix!

**Comment by mattgodbolt** [comment]
(also note as a workaround; if you provide your own `main()` that prevents the built-in stub being created)

**Comment by pcordes** [comment]
New suggestion: `int main(void){return 0;/*stub provided by Compiler Explorer*/}`

gcc4 and earlier with -xc default to `-std=gnu89`, where there's no C++-style implicit `return 0` at the end of main.  So [we get a warning with -Wall about the stub main](https://godbolt.org/g/HhRp4R).

`int main(void)` is explicitly allowed by the C and C++ standards, avoiding the need to (void)cast the parameters to avoid unused warnings.  (http://stackoverflow.com/a/3711188/224132).  I also checked my proposed stub with and without -xc on new and old clang/gcc, and got no warnings.

**Comment by mattgodbolt** [comment]
Sounds good! Will replace and update the site (it's updating now with another change, so sometime later!)
