### ISSUE TITLE
ICC Catastrophic Error

### ISSUE THREAD

**Issue by haneefmubarak** [mattgodbolt/gcc-explorer#108]
Came up somewhere in the last two weeks:

Selecting `x86 icc 13.0.1` fails if `#include <string.h>` is present and throws this error:

```
opt/intel/composer_xe_2013.1.117/compiler/include/stddef.h(13): catastrophic error: cannot open source file "stddef.h"
#include_next <stddef.h>
^
compilation aborted for /tmp/gcc-explorer-compiler116214-38-bn50av/example.cpp (code 4)
Compilation failed
```

Based on commit history from [here](https://github.com/mattgodbolt/gcc-explorer/commits/master) and [the image build repo](https://github.com/mattgodbolt/gcc-explorer-image/commits/master),  my best guess would be that either something weird occurred in the image build process, or that it has something to do with 77756b6a69, but I honestly can't seem to find anything in etiher that would cause this.

**Comment by mattgodbolt** [comment]
Thanks for the report. I too would suspect multiarch as being the culprit. Will investigate.

**Comment by mattgodbolt** [comment]
Was actually ICC relying on "PATH" being set (!). Fixed now.
