### ISSUE TITLE
Clang --analyze support

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/gcc-explorer#110]
Would be nice to detect clang's analyze output and show something nicer than a big XML document:

http://goo.gl/oWoVZS

(reported via twitter: https://twitter.com/lefticus/status/712052885530419200 by @lefticus)

**Comment by mattgodbolt** [comment]
From my own investigations at work, it seems running `clang --analyze` directly is frowned upon, and in fact may actually go away (which is a shame!). There's a ton of extra gook in `scan-build` (which sadly doesn't work in my work setup, but that's another story) which does parsing and formatting tweaks. 

Looks like there's an option to output HTML, which could be made to work I guess, provided the command-line flags don't change or go away, and provided I can scrub the output HTML for XSS attacks. (oh, security...)

**Comment by lefticus** [comment]
Yeah, this should probably just be closed. I don't use scan-build at all either, that seems to only really be supported on MacOS IMO. I use clang-tidy directly with the json build script generated from CMake. But none of this is really what compiler-explorer is for.

**Comment by mattgodbolt** [comment]
Thanks for the feedback. I may reopen if I ever suss out `clang --analyze` for work!
