### ISSUE TITLE
Make it easy to get non-shortened permalink URLs (mainly for stackoverflow)

### ISSUE THREAD

**Issue by pcordes** [mattgodbolt/gcc-explorer#112]
Stackoverflow has banned URL shorteners including goo.gl (because of spam / Rickrolls and worse).  URL length limits are [not really a problem in posts](http://meta.stackoverflow.com/questions/319549/how-are-we-supposed-to-post-godbolt-links-now-that-url-shortening-is-blocked), so posting full URLs is the way forward.  (SO will have to do something about comments, because none of the possible workarounds for long URLs in comments are implemented yet.)

Also, I've had [at least one goo.gl link break on me](http://stackoverflow.com/questions/6996764/fastest-way-to-do-horizontal-float-vector-sum-on-x86/35270026#35270026), so there is real value in saving full URLs, and encouraging people to do that where convenient.

---------

The UI options I can think of are:

* two link buttons: permalink and shortlink (or perma-shortlink?)

* clicking permalink pops up two text fields.  (Downside: the generated shortlink is "wasted" if nobody ever uses it.  It's not like google's database is going to fill up from this, but it still bugs me.)

* Update the browser's URL bar to the full URL on click of permalink.  Or still have two buttons, one that just does that?  This was suggested by Matt in an SO comment.

  Advantage: browser restarts won't lose state.  (They'll at least come back to the last permalink "save").  With multiple godbolt tabs open, restarting Chromium tends to make them all use the same form-saving data.

 Disadvantage: this might defeat browser form-data saving, and always revert to the URL-bar URL even when the current contents don't match, when closing / reopening a tab or the whole browser.

**Comment by mattgodbolt** [comment]
Agreed. I also think I should take the opportunity to tidy up/make the format more compact. (perhaps using rison.js).

**Comment by mattgodbolt** [comment]
Many comments on short URL format from @pcordes in #113

**Comment by mattgodbolt** [comment]
Released (may require an "F5" reload). buttons are "full link" and "short link". Also has a copy-to-clipboard button to save on wear and tear on your ctrl-C key :)
