### ISSUE TITLE
permalink isn't working on chromium 49

### ISSUE THREAD

**Issue by pcordes** [mattgodbolt/gcc-explorer#115]
In Chromium, when the location bar URL is just https://gcc.godbolt.org/, clicking permalink opens the Permalink text field, but it's stuck on a greyed out "Loading".  The Javascript console shows:

```apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.en.5s2JpObNt_4.O/m=plusone…/d=1/ed=1/am=AQ/rs=AGLTcCOZZh5LaFDo6a2mblq-IF0izNwoQA/cb=gapi.loaded_0:250 Uncaught TypeError: Cannot read property 'length' of undefined```

From `about:`
```
Chromium	49.0.2623.87 (Developer Build) Ubuntu 15.10 (64-bit)  
JavaScript	V8 4.9.385.28
```

When the URL bar is a full URL like [this one](https://gcc.godbolt.org/#compilers:!((compiler:g530,options:'-xc+-std%3Dgnu11+-O3+-Wall+-march%3Dhaswell',source:'int+f(int+x)+%7B+return+!!x%3B+%7D%0A_Bool+fbool(_Bool+x)+%7B+return+!!x%3B+%7D%0A%0A/*int+main(int+argc,+char**argv)+%7B%0A++return+puts(argv%5B1%5D)%3B%0A%7D%0A*/%0A%23include+%3Cstring.h%3E%0A%23include+%3Cstdint.h%3E%0A%23include+%3Cstdbool.h%3E%0A%0Abool+check_palindrome(unsigned+long+len,+const+char*str)%3B%0Aint+main(int+argc,char**argv)%7B%0A++return+!!check_palindrome(strlen(argv%5B1%5D),+argv%5B1%5D)%3B%0A%7D')),filterAsm:(commentOnly:!t,directives:!t,intel:!t,labels:!t),version:3), there's no problem.  The permalink button works like it used to.  (But with a godbolt.org URL, yay!  Still have to manually expand it to remove shortening for full future-proofing when I don't need a short URL, though, boo!)

In Firefox 45, it works fine, even when the location-bar URL is just gcc.godbolt.org

**Comment by mattgodbolt** [comment]
That's an odd one! From the little stacktrace you show it looks like there's an issue in the Google API itself. That said; there's a user callback in there too. My money's on that. I'll try and repro. I'm about to push a whole new version of compiler explorer; can you re-test with that too?

**Comment by mattgodbolt** [comment]
Weird. I tried with Chromium 48 (the one I had on my laptop) and on a head release (Chromium 51.0.2693.0) and they both worked OK.

I'll try and find an exact version match another time. (I don't have an Ubuntu 15.10 machine around)

**Comment by pcordes** [comment]
I tried again with the console already open when I clicked "short link" on gcc.godbolt.org:

```
cb=gapi.loaded_0:250 Uncaught TypeError: Cannot read property 'length' of undefined(anonymous function) @ urlshorten-google.js:24h.Ph @ cb=gapi.loaded_0:257xs @ cb=gapi.loaded_0:260Wq @ cb=gapi.loaded_0:260_.C.mA @ cb=gapi.loaded_0:260Ap @ cb=gapi.loaded_0:254
```

The "short link" button worked fine on `rust.godbolt.org`, though.  (BTW, Rust looks really interesting, with i32.count_ones() being part of the language, and same for arithmetic right shift and other things that are complicated or impossible to write efficiently *and* portably in C.  I'm pretty much tired of the C standard being much weaker than necessary when all modern ISAs are 2's complement etc. etc.)

**Comment by mattgodbolt** [comment]
Interesting! That line corresponds to the code accessing the global
"OPTIONS" variable...which very much should be set (
https://github.com/mattgodbolt/gcc-explorer/blob/master/static/urlshorten-google.js#L24).
can you do a quick favour and see what "OPTIONS" is by typing just
"OPTIONS" into the javascript console. If that comes up with anything, also
try OPTIONS.googleShortLinkRewrite please?

Thanks!

(and yes, definitely re: Rust!)

**Comment by mattgodbolt** [comment]
I wonder if the "options" object is being incorrectly cached from before. Can you try a "shift-F5" reload of the page and see if that fixes it too... (with reference to #63 )

**Comment by malcolmr** [comment]
(I saw this too, briefly, but I couldn't reproduce.)

@mattgodbolt I'm pretty sure that's it. `client-options.js` is cacheable (by intermediates) for a week, because it's `Cache-Control:public, max-age=600000`, while `urlshorten-google.js` is cacheable (privately) for 10 minutes (`Cache-Control:max-age=600`).

`OPTIONS.googleShortLinkRewrite` won't be set at all with an old version of `client-options.js`, hence "Cannot read property 'length' of undefined" when you check `OPTIONS.googleShortLinkRewrite.length`.

**Comment by mattgodbolt** [comment]
Makes sense. Thanks Malcolm: I will have to get #63 sorted soon...

**Comment by pcordes** [comment]
Sorry I didn't reply earlier.  It's working now on the same browser, so it probably was just a caching issue.
