### ISSUE TITLE
Vertical scroll bar always present

### ISSUE THREAD

**Issue by lefticus** [mattgodbolt/gcc-explorer#119]
I cannot seem to have a high enough resolution screen to get all of the layout fitting without a vertical scrollbar. I'm running at 1920x1080. This behavior seems to been introduced in a recent update.

**Comment by mattgodbolt** [comment]
Thanks; site's updating now...give it 10-15mins or so and then refresh (might still need a shift-F5 refresh as I've not fixed #63 yet...)  Let me know!

**Comment by lefticus** [comment]
much better, thanks

**Comment by mattgodbolt** [comment]
No worries! Thanks for raising the bug...I'd kinda become blind to it :grin:
