### ISSUE TITLE
Incorrect colouring

### ISSUE THREAD

**Issue by msoosgds** [mattgodbolt/gcc-explorer#128]
On this link: https://godbolt.org/g/5WTSr3 The memset is coloured with a white background on the left, but the call to `__memset_chk` is coloured green on the right. It's as if the memset was optimized out but it isn't, it actually gets generated.

**Comment by mattgodbolt** [comment]
Hi!

The colouring is based purely off GCC's debug information...I'll have a
look and see if I'm incorrectly parseing it!

Thanks!

**Comment by mattgodbolt** [comment]
If you take a look at: https://godbolt.org/g/xMKis7 you can see, around line 70/71 of the asm output that the compiler is telling me that the `mov $5,edx ; call __memset_chk` is in `.loc 2 85 0` -- which means line 85 of file "2". File "2" is defined just above on line 43 as being `/usr/include/x86_64-linux-gnu/bits/string3.h` -- so GCC is attributing the call to memset_chk to that piece of code, not any that you typed in.

In newer compilers that doesn't seem to happen: I'm not quite sure why, but unless there's a compiler option I don't know about, I don't think there's much I can do.

Thanks for filing the bug: if you have any thoughts on how to fix this or suggestions, don't hesitate to reopen.

**Comment by msoosgds** [comment]
Thanks! To be honest, I think some of this dependency checking should be better in compilers. It would really help, especially when it comes to symbolic execution and bug tracing (as both use slicing and other techniques to cut out irrelevant code). The thing is, right now, it's all a bunch of hacks, so properly calculating dependencies is impossible. Maybe some more mathematical compilers will come one day (CompCert being a prime candidate) that can do this tracking _very_ precisely. Until then, I'll just enjoy godbolt.org ;) Thanks for the tool, it rocks!
