### ISSUE TITLE
Throwing "502 Bad Gateway"

### ISSUE THREAD

**Issue by haneefmubarak** [mattgodbolt/gcc-explorer#129]
The [site](https://gcc.godbolt.org/) appears to be [down](http://archive.is/S4S3Y):

![503 Bad Gateway](http://archive.li/S4S3Y/1680c7b5d0b01f34e55d8076802317dfac5ca83b/scr.png)

and `nginx` is throwing a `502 Bad Gateway` HTTP error.

**Comment by mattgodbolt** [comment]
Indeed - have restarted it for now but seems it keeps running out of RAM. As this has happened a few times in the last day and not at all for many weeks before can only assume some bad request is causing the issue. Am heading to bed now and will dig more in the morning, but the site should be back up soon.

**Comment by haneefmubarak** [comment]
Thanks for the quick look Matt! I'll see if I can figure out what it might be in the meantime (might be able to just send in a pull request if it's something easily fixed).

**Comment by mattgodbolt** [comment]
Thanks. All seems OK now, though memory usage is slowly ticking up again.

**Comment by haneefmubarak** [comment]
@mattgodbolt sent you an email that may help if the bad requests are intentionally malicious or even otherwise

**Comment by haneefmubarak** [comment]
Also, could you paste the output of this command from the server(s) that serve GCC Explorer:

```bash
ps aux  | awk '{print $6/1024 " MB\t\t" $11}'  | sort -nr | head -n 25
```

Quick explanation:

1. List all processes by all users across the system
2. Rewrite lines to only display memory usage and process path
3. Sort the line by the numbers in reversing order
4. Output the first 25 lines

**Comment by mattgodbolt** [comment]
Sure thing:

```
$ ps aux  | awk '{print $6/1024 " MB\t\t" $11}'  | sort -nr | head -n 25
236.898 MB		node
46.0977 MB		node
39.5 MB		/usr/bin/docker
36.8906 MB		node
31.8516 MB		node
31.3164 MB		node
12.7891 MB		docker
11.8008 MB		docker-proxy
11.7461 MB		docker-proxy
11.5859 MB		docker-proxy
11.5234 MB		docker-proxy
11.5195 MB		docker-proxy
11.4258 MB		docker-proxy
10.5039 MB		docker-containerd
9.05078 MB		remote_syslog
6.21094 MB		/sbin/init
5.32031 MB		/bin/logspout
4.46094 MB		-bash
4.30078 MB		docker-containerd-shim
4.15234 MB		docker-containerd-shim
4.14844 MB		docker-containerd-shim
4.125 MB		sshd:
4.125 MB		docker-containerd-shim
4.12109 MB		docker-containerd-shim
3.60938 MB		nginx:
```

Not sure how useful that is: GCC explorer is made up of 7 docker images running in tandem:

* nginx frontend
* GCC Explorer running on Ubuntu 14.04 with most of the compilers
* GCC Explorer running on Ubuntu 12.04 with some old compilers that I watned to keep that only have installers on 12.04
* Rust Explorer
* D Explorer
* Go Explorer

There's also some other bits and pieces, including a logspout container that sends logs up for aggregation in papertrail (https://papertrailapp.com/)

See https://github.com/mattgodbolt/gcc-explorer-image/ for the full setup.

My first point would be to re-enable the memory watches (e.g. using something like https://hacks.mozilla.org/2012/11/tracking-down-memory-leaks-in-node-js-a-node-js-holiday-season/ ), though the last time I discovered a leak using that it was still really tricky to isolate.

For what it's worth, only the main GCC Explorer docker instance is the one that dies. When it dies, this is the logs from papertrail:

```
May 28 19:07:42 b56702c656fa gcc:  FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory 
May 28 19:07:42 b56702c656fa gcc:  <--- Last few GCs ---> 
May 28 19:07:42 b56702c656fa gcc:  13334638 ms: Scavenge 1400.7 (1436.3) -> 1400.7 (1436.3) MB, 4.5 / 0 ms (+ 0.4 ms in 1 steps since last GC) [allocation failure] [incremental marking delaying mark-sweep]. 
May 28 19:07:42 b56702c656fa gcc:  13334671 ms: Mark-sweep 1400.7 (1436.3) -> 1395.3 (1436.3) MB, 32.9 / 0 ms (+ 16.0 ms in 752 steps since start of marking, biggest step 0.4 ms) [last resort gc]. 
May 28 19:07:42 b56702c656fa gcc:  13334695 ms: Mark-sweep 1395.3 (1436.3) -> 1394.6 (1436.3) MB, 23.8 / 0 ms [last resort gc]. 
May 28 19:07:42 b56702c656fa gcc:  <--- JS stacktrace ---> 
May 28 19:07:42 b56702c656fa gcc:  ==== JS stack trace ========================================= 
May 28 19:07:42 b56702c656fa gcc:  Security context: 0x39d435f37399 <JS Object> 
May 28 19:07:42 b56702c656fa gcc:      1: destroySoon [net.js:426] [pc=0x267621469834] (this=0x3ba350897d9 <a Socket with map 0x3f520ec7661>) 
May 28 19:07:42 b56702c656fa gcc:      2: onSocketEnd [net.js:~236] [pc=0x26762112fa02] (this=0x3ba350897d9 <a Socket with map 0x3f520ec7661>) 
May 28 19:07:42 b56702c656fa gcc:      3: emit [events.js:~117] [pc=0x267621181f3c] (this=0x3ba350897d9 <a Socket with map 0x3f520ec7661>,type=0x3a9035e2e5d1 <String[10]: _socketEnd>) 
May 28 19:07:42 b56702c656fa gcc:      4: onread [net.js:~501] [pc=0... 
May 28 19:07:42 b56702c656fa gcc:  /run.sh: line 13:    75 Aborted                 (core dumped) node app.js --env amazon --port 10240 --lang C++ 
```

and the time before:

```
May 28 14:52:39 47cfa8888617 gcc:  <--- JS stacktrace ---> 
May 28 14:52:39 47cfa8888617 gcc:  ==== JS stack trace ========================================= 
May 28 14:52:39 47cfa8888617 gcc:  Security context: 0x2fb7e2437399 <JS Object> 
May 28 14:52:39 47cfa8888617 gcc:      1: slowToString [buffer.js:348] [pc=0x18d0644d15b5] (this=0x1fce71ace381 <an Uint8Array with map 0xde7dc2f70d1>,encoding=0x2fb7e24ab741 <String[4]: utf8>,start=0,end=55170) 
May 28 14:52:39 47cfa8888617 gcc:      2: toString [buffer.js:~375] [pc=0x18d06442e445] (this=0x1fce71ace381 <an Uint8Array with map 0xde7dc2f70d1>) 
May 28 14:52:39 47cfa8888617 gcc:      3: arguments adaptor frame: 3->0 
May 28 14:52:39 47cfa8888617 gcc:      4: write [string_decoder.js:129] [pc=0x18d0644fea68] (this=0x2fb7... 
May 28 14:52:39 47cfa8888617 gcc:  FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory 
May 28 14:52:39 47cfa8888617 gcc:  /run.sh: line 13:    76 Aborted                 (core dumped) node app.js --env amazon --port 10240 --lang C++ 
```

In retrospect I should have looked for the core file: that would have given a decent clue as to what's taking up all the RAM!

Any help appreciated!

**Comment by haneefmubarak** [comment]
hmmm... How big is the instance's memory and is swap enabled? Earlier this year I had some NodeJS web-facing machines OOM-kill `node`. Also, is there a memory limit set on the Docker containers?

That being said, it definitely look like something's leaking - I'll clone the repo and have a look.

**Comment by mattgodbolt** [comment]
The instance has 4GB of RAM, and swap is not enabled. It seems node.js has a 1.4GB heap limit by default; which really ought to be more than enough! Luckily the OOM killer wasn't involved here: though in the bug I emailed you about (the previous "leak") the OOM killer was involved as I was running on tiny instances with only 1GB of RAM in total (!)

Thanks!

**Comment by mattgodbolt** [comment]
(Forgot to answer: there's no Docker limit that I'm aware of setting...at
least not on purpose!)

**Comment by mattgodbolt** [comment]
All has been quiet on this one for a long while now. Still not really sure what casued it, but closing until it crops up again.
