### ISSUE TITLE
Rust compiled with optimizations shows empty assembly

### ISSUE THREAD

**Issue by vks** [mattgodbolt/gcc-explorer#139]
Rustc 1.9.0 seems to be the last version that works with `-O`. All newer version show an empty assembly if the (default) "Directives" filter is enabled.

**Comment by mattgodbolt** [comment]
Thanks for the report: any clues on why this might be would be welcome as I'm a little stumped!

**Comment by vks** [comment]
It seems like the filtering is working as intended. When enabling optimizations with Rust > 1.9 I can't see any assembly instructions anymore for some reason.

When looking at https://play.rust-lang.org (using stable, which should be Rust 1.11), there is a `.LBB0_1` section with the assembly which is completely missing on rust.godbolt.org. Note that this section name only occurs with optimizations, otherwise the section names are very similar for both websites.

Could it be that the `.LBB0_1` section is filtered out completely for some reason, even if all filters are disabled? (There are more `.LBB0_*` sections that are missing.)

**Comment by mattgodbolt** [comment]
Interesting! Thanks for investigating. There is still some filtering done
on the server: I can only imagine there's something funny going on. I'll
take a look tonight, or if you're brave
https://github.com/mattgodbolt/gcc-explorer/blob/master/lib/asm.js#L38 has
the code.

**Comment by CryZe** [comment]
Adding a `#[no_mangle]` attribute to the top-level functions fixes the problem. So it's either a problem with name mangling or Rust doesn't include mangled top-level functions in the output anymore.

**Comment by mattgodbolt** [comment]
Thanks @CryZe for the update here - a handy clue!

**Comment by mattgodbolt** [comment]
I haven't had time to dig into this further yet...hopefully this weekend, unless some kind soul who understands Rust better than me takes pity and has a look.

**Comment by silmeth** [comment]
As I wrote on Google+:

It looks good with `--crate-type lib -O` (or even-more-optimized with `--crate-type lib -C opt-level=3`). Looks like rustc optimizes out everything unused in static libs.

[Link to an example](https://godbolt.org/g/OISbuv)

Also – everything is removed from `cdylib`, but works OK with `dylib`. Which makes sense, as Rust-mangled functions wouldn’t be usable from C code.

So maybe it just removes all mangled functions in a static lib when nothing is actually lining to them? Compiler works as it should when creating a dynamic lib. So you could just change the target to dynamic lib, or encourage people to use non-mangled functions (and do so in given examples).

**Comment by silmeth** [comment]
Also creating an executable `bin` target with an entry point correctly compiles everything, [with inlining short functions](https://godbolt.org/g/dQxhWn).

It’s interesting that a public function gets inlined ;-) – but again, that’s probably because it would get mangled anyway, and so be unusable from any other language or with a different compiler version, [unmangled one doesn’t get inlined](https://godbolt.org/g/s7H4vb).

**Comment by vks** [comment]
What is the best way to fix this issue? Should `--crate-type lib` be added automatically or at least to the example?

**Comment by mattgodbolt** [comment]
If that's all it takes, then I'm already passing some canned options to the
compiler. I can ensure its type is lib instead. Will take a look at doing
this. Thanks all!

**Comment by silmeth** [comment]
[Here you can read about various types of Rust libraries](https://doc.rust-lang.org/reference.html#linkage).

Basically:
* `lib` is whatever rust compiler chooses,
* `staticlib` is a typical `.a` static library for interoperability with C code and FFI,
* `dylib` is a dynamic `.dll` or `.so` library (usable from both Rust and FFI),
* `cdylib` (not described there unfortunately) seems to be a `dylib` for FFI,
* `rlib` is a Rust static library (so like `staticlib` but exposing all public Rust-mangled symbols.

So I’d choose here `--crate-type rlib` as a most typical rust output format (which shouldn’t optimize out anything `pub`).

`lib` can do basically anything, depending on the platform, so perhaps it isn’t the best options for showing compiler’s behaviour (on the other hand it *is* the default, and I believe it typically produces `rlib`s). `dylib` is the one that you should use if you want to create a dynamic Rust library.

`staticlib` and `cdylib` are two target formats for FFI, so the compiler is free to optimize everything that is not `#[no_mangle]`.

**Comment by steveklabnik** [comment]
> `cdylib` (not described there unfortunately)

[it is in nightly](https://doc.rust-lang.org/nightly/reference.html#linkage), the docs lagged a bit.

**Comment by vi** [comment]
Why not just add `#[no_mangle]` to the default `square` example?

**Comment by mattgodbolt** [comment]
I'd really like Compiler Explorer to work with "normal" code instead of
specially formatted/annotated code. I agree `#[no_mangle]` is a workaround,
but most code isn't written that way. If we can find a way to "fix" the
underlying problem that'd be much better.

**Comment by silmeth** [comment]
The underlying problem is that by default Compiler Explorer sets the `--crate-type staticlib` flag, which tells rustc to compile code for C-API FFI static library, which does not have to preserve any non-`#[no_mangle]` nor non-`extern` symbols, so they get optimized out.

To fix this you just need to change that default flag to something more Rusty – like `--crate-type rlib`. Or add `#[no_mangle]` to code examples.

I don’t see anything complicated to fix here. ;-)

**Comment by mattgodbolt** [comment]
Right: that's my plan. I'm backed up on a whole bunch of refactoring work
in trunk that's holding up changing the site to use that crate type by
default.

**Comment by mattgodbolt** [comment]
Work around appears to be effective. Testing tonight, hoping to do a site release tomorrow.

**Comment by mattgodbolt** [comment]
Thanks everyone: the fix is now live. Please check it out on rust.godbolt.org and let me know if you see any further issues by replying here.

**Comment by bradleygibson** [comment]
Odd--am I the only one still seeing this issue?

**Comment by mattgodbolt** [comment]
(@ brad) - are you compiling with optimizations and no public functions?

**Comment by bradleygibson** [comment]
@mattgodbolt It turned out I was.  It made sense after I figured it out :)

**Comment by mattgodbolt** [comment]
Great stuff! just making sure I hadn't missed anything!
