### ISSUE TITLE
Colorise option is broken

### ISSUE THREAD

**Issue by gabrieldevillers** [mattgodbolt/gcc-explorer#140]
Hi Matt :)
I think it is broken.
It was working in commit ef9614e57051ebd415b0d4f31aab92330e7527f8

**Comment by mattgodbolt** [comment]
Hi!

Yes, I've been meaning to get back to you: I'm working on a huge refactor in the branch "goldenlayout" to get a completely new UI. The master branch is a little broken I'm afraid: I will try and get it fixed up though.

That said: what's broken? I just pulled latest from master and aside from some slightly broken HTML the colourise seems to be working.

--matt
![screenshot](https://cloud.githubusercontent.com/assets/633973/17970701/534b5fda-6a9d-11e6-8af5-7353d28ef4a8.png)

**Comment by Voxelf** [comment]
Thanks for keeping up the work !

The first problem is that if disabled the color does not go away in the editor.
The second is that I had managed to have color only in the starred slot (as I thought that wrong colors would be displayed in all but one slot), with the colors changing immediately if you changed the starred slot.
If you think it is better to have colors in all slots it's fine, but there risk to be useless lines of code in static/compiler.js

**Comment by mattgodbolt** [comment]
Thanks for the reply:

1. Colour not going away is a foolish bug: will fix!
2. I merged all the colours together. I fixed the issue (I think!) with picking a set of colours that work across all active slots, so the colours ought to "just work" now...I'll fix it if not. (see below)

Thanks, Matt
![colourising](https://cloud.githubusercontent.com/assets/633973/17972321/f991380a-6aa3-11e6-89f1-1316f53966f4.png)

**Comment by Voxelf** [comment]
Nice! Thanks, I'll test that when I see new commits.

**Comment by mattgodbolt** [comment]
Heyas! I tried to email you but the email I had for you bounced: I'd like to share something with you that's not quite ready for "prime time" : can you ping me an email at matt@godbolt.org? thanks!

**Comment by mattgodbolt** [comment]
So far I think the colourisation works as expected. Feel free to open if you can find an example where it's broken!
