### ISSUE TITLE
Favorite compilers

### ISSUE THREAD

**Issue by Zingam** [mattgodbolt/gcc-explorer#142]
It would be very nice if there is an option to select and quickly switch between a couple of compilers. I like that assembly code feature and I'd like to be able to quickly switch and compare the generated code by different compilers.
That's because the list of all compilers is too long.

**Comment by mattgodbolt** [comment]
Great idea; thanks. I'm working on a whole set of features that _might_ address this. Keep an eye out for a public beta of the new features sometime next week and let me know if you think this is addressed appropriately!

**Comment by Zingam** [comment]
Will the project also support execution of the compiled code?

**Comment by mattgodbolt** [comment]
That's currently not a goal for Compiler Explorer.

**Comment by mattgodbolt** [comment]
@Zingam does the new UI satisfy your needs? As in, you can now have two compilers up (and/or put them in tabs should you prefer).

**Comment by Zingam** [comment]
Good job! Thanx!

**Comment by mattgodbolt** [comment]
Also note that if you need to switch between compilers you can either put
two compiler panes up and have them both compile at the same time. You can
also type type names or part of the names of the compiler into the compiler
drop down to filter the list.

Thanks !

**Comment by Zingam** [comment]
Just a side question. Do the optimization flags produce valid results?

**Comment by mattgodbolt** [comment]
I'm not sure I understand the question -- all the flags are passed to the compiler, and I display whatever the compiler outputs. So if the question is "does the compiler generate correct code when optimizations are on" then you'll have to ask the individual compiler developers :)
