### ISSUE TITLE
Binary addresses hard to read when compiled with -m32

### ISSUE THREAD

**Issue by tim-becker** [mattgodbolt/gcc-explorer#144]
When using the compiler option `-m32` and selecting the binary mode, the instruction addresses overlap with the assembled bytes. Presumably this view was only tested with 64-bit binaries, where the addresses are smaller.

<img width="316" alt="screen shot 2016-09-29 at 4 38 32 pm" src="https://cloud.githubusercontent.com/assets/4476584/18971547/670e327c-8663-11e6-91d2-8d3c3de3f4e7.png">

**Comment by mattgodbolt** [comment]
Thanks for the report. Yes you guessed right :-) I've not tested 32bit! In
fact it didn't use to work at all!

**Comment by mattgodbolt** [comment]
Fixed; but not pushed to live site...yet...hoping to get this out as part of a big release I have planned!
