### ISSUE TITLE
Add Erlang ?

### ISSUE THREAD

**Issue by ldemailly** [mattgodbolt/gcc-explorer#165]
I know it's a bit far fetched, but would you consider adding

apt-get install erlang

to your image

and support for

`erlc -S square.erl`

with square.erl being:

``` Erlang
-module(test).
-compile(export_all).

square(N) -> N * N.
```

produces (for instance) - cutting useless parts:

``` Erlang
{function, square, 1, 2}.
  {label,1}.
    {line,[{location,"square.erl",4}]}.
    {func_info,{atom,test},{atom,square},1}.
  {label,2}.
    {line,[{location,"square.erl",4}]}.
    {gc_bif,'*',{f,0},1,[{x,0},{x,0}],{x,0}}.
    return.
```

it'd be super neat ! (to tie it back to the source based on the line decoration)

Thanks!

**Comment by mattgodbolt** [comment]
I have a similar request: #12 - I'm really not sure this is Compiler Explorer's sweet spot. Generating assembly and displaying the results is what CE is good at: adding every language under the sun and its own backend representation is rather out of scope. At least: I'm not likely to add support myself.

That said; if someone had a sensible patch I'd be happy to consider it.

**Comment by ldemailly** [comment]
I understand, trying to get gcc-explorer up and running I get weird errors, from npm logs:

npm ERR! Linux 4.0.9-68_fbk12_4058_gd84fdb3
npm ERR! argv "/usr/local/fbcode/gcc-4.9-glibc-2.20-fb/bin/node-4.3.2" "/usr/local/bin/npm" "install"
npm ERR! node v4.3.2
npm ERR! npm  v3.5.3
npm ERR! code ENETUNREACH
npm ERR! errno ENETUNREACH
npm ERR! syscall connect

npm ERR! connect ENETUNREACH ::ffff:151.101.52.162:443 - Local (:::0)
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>


and in the log file:

153 info attempt registry request try #1 at 20:24:06
154 http request GET https://registry.npmjs.org/underscore-node
155 info retry will retry, error on last attempt: Error: connect ENETUNREACH ::ffff:151.101.52.162:443 - Local (:::0)
156 info retry will retry, error on last attempt: Error: connect ENETUNREACH ::ffff:151.101.52.162:443 - Local (:::0)
157 info retry will retry, error on last attempt: Error: connect ENETUNREACH ::ffff:151.101.52.162:443 - Local (:::0)
158 info retry will retry, error on last attempt: Error: connect ENETUNREACH ::ffff:151.101.52.162:443 - Local (:::0)
159 info retry will retry, error on last attempt: Error: connect ENETUNREACH ::ffff:151.101.52.162:443 - Local (:::0)
160 info retry will retry, error on last attempt: Error: connect ENETUNREACH ::ffff:151.101.52.162:443 - Local (:::0)

that address is a bit fishy (seems to be the ipv4 for www.fashionista.com !?)

**Comment by mattgodbolt** [comment]
That's super weird: seems like `npm` can't reach the internet...I'm no `npm` expert at all, it's a common way of installing `node` libraries...and yes, I agree it looks like the bug you linked. :( Sorry!

**Comment by mattgodbolt** [comment]
I've been thinking hard on this. I'd be happy to consider a patch, but I'd like Compiler Explorer to concentrate on languages that compile to assembler, so I'm going to close this issue to keep the bug list somewhat manageable. Feel free to continue discussing here, and/or over email.

**Comment by ldemailly** [comment]
makes sense. I'm personally done with erlang for now so I won't push this :)
