### ISSUE TITLE
Make 'share' links more discoverable

### ISSUE THREAD

**Issue by lefticus** [mattgodbolt/gcc-explorer#168]
I think the link buttons on the new UI are less visible then they were on the original UI. 

Suggest consider making them a bit more visible, perhaps by using the universal "share" icon http://fontawesome.io/icon/share-alt/ beside them?

Feel free to disagree on their discoverability or not.

**Comment by mattgodbolt** [comment]
Awesome stuff. I've also just finished an "Embedded" link...advice on improving the "link" stuff welcomed. Now I have three text links on the top left ("Short Link | Full Link | Embed") and all of those could be considered "sharing" too...

UI is hard!

**Comment by mattgodbolt** [comment]
I guess you meant those...there's the "Share" menu on the top right too!

**Comment by lefticus** [comment]
Yeah, I meant the shortlink/fulllink buttons specifically. The concept of sharing on the page (the site it self? The project? The currently displayed code?) Feels a bit muddy.

**Comment by mattgodbolt** [comment]
Right...the whole thing is confusing, which is unfortunate! I'll have a think before I release the embedded view.

**Comment by mattgodbolt** [comment]
So...what do we think of the new setup? Is this better or worse? :)

**Comment by lefticus** [comment]
Definitely better

**Comment by mattgodbolt** [comment]
Sweet: thanks!
