### ISSUE TITLE
Green background colour blends in with register colourisation

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/gcc-explorer#170]
As reported by Herb Sutter:
![unnamed](https://cloud.githubusercontent.com/assets/633973/19993322/b770838a-a212-11e6-80fc-0f5b5c7001bc.png)

**Comment by hsutter** [comment]
In general, dark/strong background colors are problematic, just make sure to pick pale ones. This is the darkest one I noticed (and happens to be the first color in your palette :)) -- I'm sure that just making it say 50% paler will get most of the way there, or just replacing it with a brighter and paler one.

It's readable on a monitor, but quickly becomes hard to read when projected on a screen during a talk, even when the projected image seems plenty bright for everything else in the talk it's not as bright as a monitor and this is noticeable.

Thanks!

**Comment by mattgodbolt** [comment]
Site updated; do take a look and let me know if you think it's better :)

**Comment by hsutter** [comment]
Much better, thanks.

**Comment by mattgodbolt** [comment]
Thanks again for the feedback!
