### ISSUE TITLE
Unused-label filtering false positive on clang's __cxx_global_var_init:

### ISSUE THREAD

**Issue by pcordes** [mattgodbolt/gcc-explorer#192]
With [this input](https://godbolt.org/g/HijqVg),  clang emits a useless __cxx_global_var_init: with non-empty code.  Godbolt's default setup removes that label but not the code, so it looks like part of `main()` (but after the RET, and separated by a blank line).

Adding a `char foo;` global variable for some reason causes the unused-label filtering to leave it in.

First noticed due to the confusion it caused, leading to the asking of http://stackoverflow.com/questions/40709969/type-deduction-when-using-a-templated-lambda-with-a-nested-struct-analyzing-po.  (I already posted an answer there clearing up the confusion and pointing out what you get from un-checking the unused-labels button)

---

(huh, inline URLs don't work on github?)

Full url: [markdown doesn't work for it](http://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(j:1,options:(colouriseAsm:'0',compileOnChange:'0'),source:'%23include+%3Ctype_traits%3E%0A%0A//char+foo%3B++//+uncomment+this+to+make+__cxx_global_var_init:+show+up+with+unused-label+filtering+on%0A%0Atemplate%3Ctypename+T%3E%09//+1%0A++auto+asdf+%3D+%5B%5D(T+x)+%7B%0A++++++struct+foo+%7B%0A++++++++T+xyz%3B%0A++++++%7D%3B%0A++++++%0A++++++return+foo%7Bx%7D%3B%0A++++%7D%3B%0A%0A%0Aint+main()+%7B%0A++return+asdf%3Cfloat%3E(3.14).xyz%3B+//2%0A%7D%0A%0A'),l:'5',n:'1',o:'C%2B%2B+source+%231',t:'0')),k:53.87367776408505,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:clang390,filters:(b:'0',commentOnly:'0',directives:'0',intel:'0'),options:'-std%3Dc%2B%2B14+-O3'),l:'5',n:'0',o:'%231+with+x86-64+clang+3.9.0',t:'0')),k:46.12632223591495,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4)

**Comment by mattgodbolt** [comment]
I've started investigating this. There's a lot of heuristics in my filtering system, and it clearly needs some tweaks...

**Comment by mattgodbolt** [comment]
The fix mentioned above should catch this and other unusual cases. I'll look to update the site with this fix later today.

**Comment by mattgodbolt** [comment]
Fix deployed: the link above now works both with and without the `char foo`
