### ISSUE TITLE
Any plans to add Microsoft compiler?

### ISSUE THREAD

**Issue by crea7or** [mattgodbolt/gcc-explorer#199]
Maybe via docker or like that. Compiler [is free](http://landinghub.visualstudio.com/visual-cpp-build-tools).

**Comment by mattgodbolt** [comment]
It's already on the beta site in an early form: gcc.beta.godbolt.org

Docker doesn't help here sadly as docker on Linux won't run docker windows
images. But WINE is just about working.

**Comment by AraHaan** [comment]
that reminds me where can I find that ```modified`` gcc build for your sute that was used for the Comodore 64 stuff from a CPPCon? I would like it try it out myself.

**Comment by mattgodbolt** [comment]
https://github.com/lefticus/x86-to-6502 ?

**Comment by mattgodbolt** [comment]
Now released on the main site.
