### ISSUE TITLE
Rust (v1.11.0) support flags `fn main` as unused

### ISSUE THREAD

**Issue by zzmp** [mattgodbolt/gcc-explorer#207]

**Comment by mattgodbolt** [comment]
Thanks; I'm hoping an upcoming fix to move to using `cratetype rlib` might either fix, or change this a lot...

**Comment by mattgodbolt** [comment]
I can't repro with the new site. Can you provide a link that repros this? Thanks!

**Comment by mattgodbolt** [comment]
I can repro now. You "just" need to make it `pub fn main()` else the compiler optimizes it away (currently I build the code as an `rlib` type.

Let me know if you have any issues with this, or if there's anything else I should consider.

**Comment by zzmp** [comment]
I cannot repro anymore, regardless of if main is pub. :)

**Comment by mattgodbolt** [comment]
Thanks for letting me know!
