### ISSUE TITLE
Assembly code disappears for Rust if I add optimization

### ISSUE THREAD

**Issue by vi** [mattgodbolt/gcc-explorer#209]
With `--crate-type staticlib -C opt-level=0` I see things on the right panel, but with `--crate-type staticlib -C opt-level=1` it shows nothing.

Maybe default example source code should have `#[no_mangle]`?:

```
// Type your code here, or load an example.

#[no_mangle]
pub fn square(num: i32) -> i32 {
  num * num
}
```

**Comment by mattgodbolt** [comment]
Duplicate of #139
