### ISSUE TITLE
Demangling doesn't work for functions with multiple vector arguments and -fabi-version=4

### ISSUE THREAD

**Issue by mgaunard** [mattgodbolt/gcc-explorer#21]
This code

``` C++
#include <xmmintrin.h>

void f(__m128 a, __m128 b)
{
}
```

doesn't demangle `f` correctly when compiled with -fabi-version=4.

-fabi-version=4 is required to distinguish __m128 and __m256 in overloads and specializations, and is therefore pretty important for any C++ AVX code.

**Comment by mattgodbolt** [comment]
This appears to have been fixed along the way (probably by a glibc update).
