### ISSUE TITLE
Demangle Rust Function Names

### ISSUE THREAD

**Issue by CryZe** [mattgodbolt/gcc-explorer#213]
Shouldn't be too hard to implement. The demangling code that Rust uses internally is here:

https://github.com/alexcrichton/rustc-demangle/blob/master/src/lib.rs#L44

**Comment by mattgodbolt** [comment]
Great stuff; thanks. Happy to accept patches, else will get to this in time.

**Comment by mattgodbolt** [comment]
This is now live
