### ISSUE TITLE
Label filtering removes jump tables

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/gcc-explorer#35]
(reported by Dennis Lubert- thanks Dennis)

Today I tried to look at some code that is evaluating into a jumptable,
like:

void foo(unsigned x)
{
swithc(x)
{
case 0:
bar0();
break;
[ same for at least case 4, otherwise it wont be a jump table. Intreting
is the optimization for three cases btw.]
default:
__builtin_unreachable();
};
}

there in asm a location is created and correctly labeled, but it
contains data like:

.quad .L3
.quad .L4
.quad .L5
etc.

and then later
.L3:
jmp bar1()
.L4
jmp bar2()

etc. but when enabling the unused labels filter, then those get removed
too.

greets

**Comment by TPolzer** [comment]
+1

**Comment by mattgodbolt** [comment]
Sorry for how long it took to get to this, but the live site has now been updated with the fix. Please let me know if anyone finds an issue with it!
