### ISSUE TITLE
Add objdump, binary view of the compilation

### ISSUE THREAD

**Issue by auselen** [mattgodbolt/gcc-explorer#37]
This is a request asking if it is possible to add objdump, binary view of the compilation. 

Sometimes you would like to see what are the binary values for the instructions being shown.

**Comment by mattgodbolt** [comment]
Been a long time coming, but hopefully the latest update addresses this. Do take a look and reopen/file new issues as you see fit.

**Comment by ouned** [comment]
is it possible for arm, too? the binary filter is grayed out on all arm compilers.

**Comment by mattgodbolt** [comment]
It will need some work as most of the arm compilers aren't set up to do
full compilation and also I need to ensure the objdump is compiled with ARM
support (I think it already is)... Will take a look over the next few weeks!
