### ISSUE TITLE
Ubuntu Clang can output intel syntax

### ISSUE THREAD

**Issue by greatwolf** [mattgodbolt/gcc-explorer#40]
By passing this switch to clang `-mllvm --x86-asm-syntax=intel` the more readable intel syntax can be shown in the assembly output.

It would be great if this can be incorporated into gcc-explorer so that the `Intel syntax` button isn't grayed out when Ubuntu clang is selected as the compiler.

**Comment by mattgodbolt** [comment]
Was fixed in 400e553116b76745822f2fdabfff85c1911b58b6
