### ISSUE TITLE
Improve code sharing URL generator

### ISSUE THREAD

**Issue by Manu343726** [mattgodbolt/gcc-explorer#42]
I have noticed that the share URL generator just inserts the code and the compiler settings in the URL.  
That works, but for large code snippets and sites with limitted URL lengths (Yes Twitter/stackoverflow, I'm talking about you...) that URLs cannot be shared easily/directly.

It would be awesome if the web generates better (shorter) urls. I think that URLs are generated in that way because GCC explorer server does not host the sourcecode, only provides a compiler frontend. But would be great if the server push the code automatically to a web like pastebin.com, and when the URL is accessed, that code is pulled from that web and written in gcc-explorer automatically.

**Comment by malcolmr** [comment]
I assume this was fixed by #47?

**Comment by mattgodbolt** [comment]
Closing; I believe it's fixed...
