### ISSUE TITLE
Add support for latest GCC and Clang

### ISSUE THREAD

**Issue by haneefmubarak** [mattgodbolt/gcc-explorer#54]
The latest GCC and Clang have arguably made fairly large performance improvements along with adding  additional functionality and flags.

Could we get the latest versions of GCC and Clang on the gcc.godbolt.org website? Here are the links (I think you're in the UK - so I chose mirror servers near there):

 - [GCC 4.9.2](http://mirrors-uk.go-parts.com/gcc/releases/gcc-4.9.2/)
 - [Clang w/ LLVM 3.5.0](http://llvm.org/releases/download.html)

Also, if possible, it'd be nice to have Intel's latest compiler if they'd give you this year's copy (the site is on 13.0.1):

 - [ICC w/ Intel Parallel Studio XE](https://software.intel.com/en-us/intel-parallel-studio-xe)

---

Also, thank you so much for creating and hosting the service, @mattgodbolt!

**Comment by mattgodbolt** [comment]
Internal changes now mean I'm free to run on Ubuntu 14.04. Still a ways off, but getting there.

**Comment by mattgodbolt** [comment]
Clang 3.5 is there (yay), and I've contacted Intel about a newer ICC. I'll look at getting GCC4.9.2 soon

**Comment by haneefmubarak** [comment]
What Ubuntu are you on? You should be able to manually add the Debian repos
from llvm.org, where they have bleeding edge clang too (clang w/ LLVM 3.6).

Thanks again for going through all this hassle to bring the compilers
backup to speed!


-- 
- Haneef Mubarak

**Comment by mattgodbolt** [comment]
The main site's on 14.04 now, so it should be pretty easy to add 3.6 and
3.5.1 etc :) Will take a look tonight

On Mon, Feb 9, 2015 at 10:37 AM, Haneef Mubarak <notifications@github.com>
wrote:

> What Ubuntu are you on? You should be able to manually add the Debian repos
> from llvm.org, where they have bleeding edge clang too (clang w/ LLVM
> 3.6).
>
> Thanks again for going through all this hassle to bring the compilers
> backup to speed!
>
>
> --
> - Haneef Mubarak
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mattgodbolt/gcc-explorer/issues/54#issuecomment-73540945>
> .
>



-- 
Matt

**Comment by mattgodbolt** [comment]
Closed with 67e249a03dd15458b0ceb5772563455fd191292e (at least for now!)

**Comment by haneefmubarak** [comment]
You got gcc {PowerPC, ARM64}, & clang 3.7? Nice.

Thanks for taking care of everything so quickly! BTW, did the Intel folks not get back to you about ICC?

**Comment by mattgodbolt** [comment]
No reply from Intel guys unfortunately :(

On Monday, 16 February 2015, Haneef Mubarak <notifications@github.com>
wrote:

> You got gcc {PowerPC, ARM64}, & clang 3.7? Nice.
>
> Thanks for taking care of everything so quickly! BTW, did the Intel folks
> not get back to you about ICC?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mattgodbolt/gcc-explorer/issues/54#issuecomment-74537980>
> .
>


-- 
Via phone: excuse typos
