### ISSUE TITLE
Convert tabs to spaces in output

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/gcc-explorer#57]
Would make copy/pasting from the asm output less surprising.

**Comment by haneefmubarak** [comment]
related question: why not use tabs in the editor? It would make editing and copy/paste there easier too.

**Comment by mattgodbolt** [comment]
Personally I don't like to use tabs: as there's disagreement in general as
to how many spaces each tab represents I prefer the clarity of just using
spaces. That's why the editor uses spaces.

On Sat, Feb 7, 2015 at 9:57 PM, Haneef Mubarak <notifications@github.com>
wrote:

> related question: why not use tabs in the editor? It would make editing
> and copy/paste there easier too.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mattgodbolt/gcc-explorer/issues/57#issuecomment-73395858>
> .
>



-- 
Matt

**Comment by kazblox** [comment]
Please give the option to use tabs regardless. It's not fine to make tabs the only option, and it's not fine to make conversion to spaces the only option either.
