### ISSUE TITLE
Make resistent to trivial DoSes

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/gcc-explorer#59]
For example:

    $ for i in $(seq 100); do (curl 'http://gcc.godbolt.org/compile' -H 'Origin: http://gcc.godbolt.org' -H 'Accept-Encoding: gzip, deflate' -H 'Accept-Language: en-US,en;q=0.8' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.91 Safari/537.36' -H 'Content-Type: application/x-www-form-urlencoded' -H 'Accept: application/json, text/javascript, */*; q=0.01' -H 'Referer: http://gcc.godbolt.org/' -H 'X-Requested-With: XMLHttpRequest' -H 'Connection: keep-alive' --data "source=%23include+%3Cstring%3E%0Astd%3A%3Astring+a()+%7B+return+%22moose$i%22%3B+%7D&compiler=g490&options=-O3+-std%3Dc%2B%2B0x&filters%5Bintel%5D=true" --compressed &); done

Is pretty good at taking down the site. In theory there should be no more than two compiles at once, but I suspect while the compiles may get gated the responses are not and so eventually the response-sending uses up too much memory.  The site dies due to the OOM killer running

**Comment by haneefmubarak** [comment]
yeah btw the site appears to be down - perhaps someone decided to try this? Maybe CloudFlare basic could help mitigate assholes.

**Comment by mattgodbolt** [comment]
Hi @haneefmubarak - what time did you observe the site down? I recently upgraded it and it was down briefly while I did so but I'd be very interested if it was down for you at another time.  I have monitoring and i didn't spot it down (other than when I upgraded it), but you never know!

I dont think CloudFlare can help with this - the issue is not web traffic, but instead the memory requirements of running many compilation jobs one after another and the buffering of the JSON reponse in memory.

**Comment by haneefmubarak** [comment]
I'm on an iPad at the moment, but it was down at the time I posted the
comment. I think you can click on that time in GitHub to show the exact
date and time.

-- 
- Haneef Mubarak

**Comment by haneefmubarak** [comment]
Perhaps rate-limiting may help? Say, if someone submits more than 1
req/sec, they get sent a timeout that keeps increasing with exponential
back off until it caps out at 256s (4.2 minutes).

To prevent accidents from locking someone out, perhaps an options could be
added so that instead of it sending a request to the server for compilation
every time the editor area gets updated, there would be a submit button
that would send a request without reloading the page (is that possible in
JS? IDK).


-- 
- Haneef Mubarak

**Comment by mattgodbolt** [comment]
"Someone" is a little hard to do: I deliberately don't use any way to
identify individuals. I could use the remote IP, but I have load balancers
etc in front which make it a little harder to find.

I do queue requests and process a maximum at a time, but I think that part
isn't working too well :)

Re: your "down time" - I wonder if something I've just spotted is the
issue: I had updated the site but the JavaScript cache time was too high
and so probably the old Javascript was being served. Was the site actually
down (Errror) or were compiles just not working?

On Mon, Feb 9, 2015 at 10:42 AM, Haneef Mubarak <notifications@github.com>
wrote:

> Perhaps rate-limiting may help? Say, if someone submits more than 1
> req/sec, they get sent a timeout that keeps increasing with exponential
> back off until it caps out at 256s (4.2 minutes).
>
> To prevent accidents from locking someone out, perhaps an options could be
> added so that instead of it sending a request to the server for compilation
> every time the editor area gets updated, there would be a submit button
> that would send a request without reloading the page (is that possible in
> JS? IDK).
>
>
>
> --
> - Haneef Mubarak
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mattgodbolt/gcc-explorer/issues/59#issuecomment-73542072>
> .
>



-- 
Matt

**Comment by haneefmubarak** [comment]
Would it be possible to auto discard the entire queue if it started
clogging up? That could help with mitigation of nonintentional surges.
Remote ip or a hash of such could possibly used for rate limiting too.
Alternatively, you could make it so that on each first page load, a nonce
is requested from another page on the same domain. That page could be set
to only hand out, say, one nonce per second total. These nonces would be
stored in a small redis instance with an expire time of say an hour.

Now, when a request is received, the nonce would be submitted along with
the code. When checked against the redis instance, if the nonce is not
found (invalid or expired), then the client JS would be required to request
another nonce. However, if the nonce is valid, then the code would be
compiled and sent back.

This sort of scheme has the advantage of getting rid of most fake requests
altogether.

---

When I visited it on the day it was down, it was mainly the compiles not
working, so I would assume it was probably the queue being back logged.

On Monday, February 9, 2015, Matt Godbolt <notifications@github.com> wrote:

> "Someone" is a little hard to do: I deliberately don't use any way to
> identify individuals. I could use the remote IP, but I have load balancers
> etc in front which make it a little harder to find.
>
> I do queue requests and process a maximum at a time, but I think that part
> isn't working too well :)
>
> Re: your "down time" - I wonder if something I've just spotted is the
> issue: I had updated the site but the JavaScript cache time was too high
> and so probably the old Javascript was being served. Was the site actually
> down (Errror) or were compiles just not working?
>
> On Mon, Feb 9, 2015 at 10:42 AM, Haneef Mubarak <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > Perhaps rate-limiting may help? Say, if someone submits more than 1
> > req/sec, they get sent a timeout that keeps increasing with exponential
> > back off until it caps out at 256s (4.2 minutes).
> >
> > To prevent accidents from locking someone out, perhaps an options could
> be
> > added so that instead of it sending a request to the server for
> compilation
> > every time the editor area gets updated, there would be a submit button
> > that would send a request without reloading the page (is that possible in
> > JS? IDK).
> >
> >
> >
> > --
> > - Haneef Mubarak
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/mattgodbolt/gcc-explorer/issues/59#issuecomment-73542072
> >
> > .
> >
>
>
>
> --
> Matt
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mattgodbolt/gcc-explorer/issues/59#issuecomment-73543584>
> .
>


-- 
- Haneef Mubarak

**Comment by mattgodbolt** [comment]
All great ideas: thanks Haneef - I'll have a think!

On Mon, Feb 9, 2015 at 11:09 AM, Haneef Mubarak <notifications@github.com>
wrote:

> Would it be possible to auto discard the entire queue if it started
> clogging up? That could help with mitigation of nonintentional surges.
> Remote ip or a hash of such could possibly used for rate limiting too.
> Alternatively, you could make it so that on each first page load, a nonce
> is requested from another page on the same domain. That page could be set
> to only hand out, say, one nonce per second total. These nonces would be
> stored in a small redis instance with an expire time of say an hour.
>
> Now, when a request is received, the nonce would be submitted along with
> the code. When checked against the redis instance, if the nonce is not
> found (invalid or expired), then the client JS would be required to request
> another nonce. However, if the nonce is valid, then the code would be
> compiled and sent back.
>
> This sort of scheme has the advantage of getting rid of most fake requests
> altogether.
>
> ---
>
> When I visited it on the day it was down, it was mainly the compiles not
> working, so I would assume it was probably the queue being back logged.
>
> On Monday, February 9, 2015, Matt Godbolt <notifications@github.com>
> wrote:
>
> > "Someone" is a little hard to do: I deliberately don't use any way to
> > identify individuals. I could use the remote IP, but I have load
> balancers
> > etc in front which make it a little harder to find.
> >
> > I do queue requests and process a maximum at a time, but I think that
> part
> > isn't working too well :)
> >
> > Re: your "down time" - I wonder if something I've just spotted is the
> > issue: I had updated the site but the JavaScript cache time was too high
> > and so probably the old Javascript was being served. Was the site
> actually
> > down (Errror) or were compiles just not working?
> >
> > On Mon, Feb 9, 2015 at 10:42 AM, Haneef Mubarak <
> notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> > wrote:
> >
> > > Perhaps rate-limiting may help? Say, if someone submits more than 1
> > > req/sec, they get sent a timeout that keeps increasing with exponential
> > > back off until it caps out at 256s (4.2 minutes).
> > >
> > > To prevent accidents from locking someone out, perhaps an options could
> > be
> > > added so that instead of it sending a request to the server for
> > compilation
> > > every time the editor area gets updated, there would be a submit button
> > > that would send a request without reloading the page (is that possible
> in
> > > JS? IDK).
> > >
> > >
> > >
> > > --
> > > - Haneef Mubarak
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/mattgodbolt/gcc-explorer/issues/59#issuecomment-73542072
> > >
> > > .
> > >
> >
> >
> >
> > --
> > Matt
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/mattgodbolt/gcc-explorer/issues/59#issuecomment-73543584
> >
>
> > .
> >
>
>
> --
> - Haneef Mubarak
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mattgodbolt/gcc-explorer/issues/59#issuecomment-73547466>
> .
>



-- 
Matt

**Comment by mattgodbolt** [comment]
Upgrading the box and various internal tweaks seem to have made it pretty robust. I just tried a big 1000-attempt DoS and it all seems "fine".
