### ISSUE TITLE
Internal GCC explorer error: ReferenceError: size is not defined

### ISSUE THREAD

**Issue by dariovillar** [mattgodbolt/gcc-explorer#60]
When running the following code in the online app http://gcc.godbolt.org/ an internal gcc explorer error raised.

```c_cpp

#include <iostream>
#include <functional>
#include <map>

using namespace std;

template<class I, class O>
function<O(I)> memoize(function<O(I)> f) {
    // Keep copies in the map of parameters passed as references
    map<typename std::decay<I>::type, O> memos;
    return [=](I i) mutable -> O {
        auto it = memos.lower_bound(i);
        if (it == memos.end() || it->first != i)
            it = memos.insert(it, make_pair(i, f(i)));
        return it->second;
    };
};

int main(int argc, char** argv) {
    function<long(const int&)> fib;
    fib = [&](const int& n) -> long {
        return n < 2 ? n : fib(n - 1) + fib(n - 2);
    };
    fib = memoize(fib);
    for (int i = 0; i < 100; ++i) {
        cout << i << ": " << fib(i) << endl;
    }
    return 0;
}
```

**Comment by mattgodbolt** [comment]
Fixed, but I'm afraid the error stems from the fact that more than 8MB of compiler output is generated (which is a limit on the public GCC Explorer site).  I'll update the site to not generate such a confusing error.

To get around this limit, run a local GCC Explorer, if possible. It should be fairly easy: just running "make" ought to start one up on a Linux machine, and editing the etc/config/gcc-explorer.defaults.properties will allow you to customise the compilers. Email me if I can help in any way!
