### ISSUE TITLE
Javascript is cached too long

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/gcc-explorer#63]
On main site, the JS etc is all max-age: giant -- causes update issues...

**Comment by malcolmr** [comment]
At the risk of grandmother/suck-eggs, the normal way to achieve this is to rename the JS to be foo-<content_hash>.js when you build, and make it cacheable indefinitely.

**Comment by mattgodbolt** [comment]
Right. I need a better build process to achieve this but I may as well also
do all the minification there too

On Tuesday, 10 February 2015, Malcolm Rowe <notifications@github.com> wrote:

> At the risk of grandmother/suck-eggs, the normal way to achieve this is to
> rename the JS to be foo-.js when you build, and make it cacheable
> indefinitely.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mattgodbolt/gcc-explorer/issues/63#issuecomment-73747686>
> .
>


-- 
Via phone: excuse typos

**Comment by mattgodbolt** [comment]
Fixed with the new UI, along with minification etc.
