### ISSUE TITLE
Colourise doesn't load/activate on permalinked pages

### ISSUE THREAD

**Issue by markisaa** [mattgodbolt/gcc-explorer#65]
If I permalink a run with colourise enabled and open the link in an incognito window, when I open it, the colourise button is depressed, but nothing shows up in color. I have to click it twice at that point to enable it, once to "disabled" colourise, and again to actually enable it.

**Comment by mattgodbolt** [comment]
Thanks for the heads-up! Can't believe I hadn't spotted this earlier. Fixed in my test branch: I'll look to deploy the fix later on!

**Comment by markisaa** [comment]
Wow. Impressive fix time. 'ppreciate it :).
