### ISSUE TITLE
Source editor does not work on a phone

### ISSUE THREAD

**Issue by malcolmr** [mattgodbolt/gcc-explorer#66]
I tried to test compiling a simple piece of code while on the train this morning, but I found that editing on my phone is extremely hard, as you don't appear to be able to move the cursor.

I'm using Chrome 40, so I think this is possibily the same as codemirror/CodeMirror#2830 / http://crbug.com/418177, and I note that CodeMirror seem to actively be working on a mobile version (http://discuss.codemirror.net/t/two-new-experimental-branches-open-for-testing-mobile-and-direction/74), so I'm mainly filing this as a tracking bug.

**Comment by mattgodbolt** [comment]
Can you re-test again please? I've updated code mirror and in my simple tests on an iPad it seems to be "better" (for some value of better!)

**Comment by malcolmr** [comment]
It's "better" (Chrome 46, Nexus 5X), though it's still really easy to nerf the input area by changing the zoom level. (Roughly speaking, it seems to lose track of the tap position->cursor position, and maps all taps to line 1, or to the top-left corner.)

I guess close this as it now kinda works?

**Comment by mattgodbolt** [comment]
With all the UI changes recently I retested (iPhone 5+; Chrome, not sure what version)...seems to work about as well as I'd hope!
