### ISSUE TITLE
line number on editor panes looks bad

### ISSUE THREAD

**Issue by auselen** [mattgodbolt/gcc-explorer#71]
Line numbers overlay actual code in Chrome.

**Comment by mattgodbolt** [comment]
Hi Ali. Can you try a page reload? I think you may have old cached CSS. I
think I've fixed this going forward. Thanks for the report!

On Tuesday, 3 March 2015, Ali Utku Selen <notifications@github.com> wrote:

> Line numbers overlay actual code.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mattgodbolt/gcc-explorer/issues/71>.
>


-- 
Via phone: excuse typos

**Comment by auselen** [comment]
It is gone after ctrl+F5.

Wow! miracles of modern caching... I had that view for a while and just found the motivation to file a report.

Thanks for the awesome work.
