### ISSUE TITLE
Better URL shortening

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/gcc-explorer#73]
I'm getting 403s now due to usage:

error: {errors: [{domain: "usageLimits", reason: "dailyLimitExceededUnreg",…}], code: 403,…}
code: 403
errors: [{domain: "usageLimits", reason: "dailyLimitExceededUnreg",…}]
0: {domain: "usageLimits", reason: "dailyLimitExceededUnreg",…}
domain: "usageLimits"
extendedHelp: "https://code.google.com/apis/console"
message: "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup."
reason: "dailyLimitExceededUnreg"
message: "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup."

@malcolmr any ideas how best to handle this?

**Comment by malcolmr** [comment]
I can't confirm, but it looks like the unauthenticated requests to the shortener API either now have a lower quota or (possibly more likely) are hitting that quota limit sooner due to higher usage.

I wrote up a big wall of text here, but it looks like you've done exactly what I was going to suggest in 787a863, so I'll delete it :-)

**Comment by mattgodbolt** [comment]
Thanks - good spot. I'm having teething trouble with it, but I'm basically
there! Sorry to disturb your evening pal :)

On Wed, Mar 18, 2015 at 1:09 PM, Malcolm Rowe <notifications@github.com>
wrote:

> I can't confirm, but it looks like the unauthenticated requests to the
> shortener API either now have a lower quota or (possibly more likely) are
> hitting that quota limit sooner due to higher usage.
>
> I wrote up a big wall of text here, but it looks like you've done exactly
> what I was going to suggest in 787a863
> <https://github.com/mattgodbolt/gcc-explorer/commit/787a863ffa8f61c4496e1053d30b717e05de327b>,
> so I'll delete it :-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mattgodbolt/gcc-explorer/issues/73#issuecomment-83104983>
> .
>



-- 
Matt

**Comment by mattgodbolt** [comment]
Fixed by 6a2d2a31183fe61c07b8434489bdeb0bfeb82ecb
