### ISSUE TITLE
what is the function "deserialiseState(state)" doing?

### ISSUE THREAD

**Issue by luoshengsheng** [mattgodbolt/gcc-explorer#76]
what is the function "deserialiseState(state)" doing?

**Comment by mattgodbolt** [comment]
It loads the UI state : which buttons are pressed, the source code being
edited and the compiler options. This is either stored in the URL
parameters (for external links) or in the browser local storage (to
preserve your edited code across reloads of the page).

On Fri, Apr 3, 2015 at 7:29 AM, luoshengsheng <notifications@github.com>
wrote:

> what is the function "deserialiseState(state)" doing?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mattgodbolt/gcc-explorer/issues/76>.
>



-- 
Matt
