### ISSUE TITLE
Disassembly is broken for Clang

### ISSUE THREAD

**Issue by ariccio** [mattgodbolt/gcc-explorer#85]
![assembly_clang](https://cloud.githubusercontent.com/assets/2142308/9213030/4b3d625a-405c-11e5-8c32-dadbe110e5a4.PNG)

Yeah, it's **GCC** explorer, not **LLVM** explorer, but it's fantastic to be able to compare the two.

**Comment by mattgodbolt** [comment]
Thanks for the report: that's very odd. I don't see that at all: can you
get a URL that's broken for me to compare with? (click the permalink button
and send that link )

Thanks!

-matt

On Tue, Aug 11, 2015 at 6:08 PM, Alexander Riccio <notifications@github.com>
wrote:

> [image: assembly_clang]
> <https://cloud.githubusercontent.com/assets/2142308/9213030/4b3d625a-405c-11e5-8c32-dadbe110e5a4.PNG>
>
> Yeah, it's *GCC* explorer, not *LLVM* explorer, but it's fantastic to be
> able to compare the two.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mattgodbolt/gcc-explorer/issues/85>.
>



-- 
Matt

**Comment by mattgodbolt** [comment]
Incorrectly closed wrong bug. Happy to look into this if you can get me a URL that shows the problem.

**Comment by mattgodbolt** [comment]
Closing now; please reopen if you can reproduce along with a link that shows the issue please!

Thanks!
