### ISSUE TITLE
Doesn't work with Link Time Optimization

### ISSUE THREAD

**Issue by ariccio** [mattgodbolt/gcc-explorer#88]
When I pass `-flto` to `Compiler options`, the `Compiler output` is `Compiled ok`, but `Assembly output` is empty.

**Comment by mattgodbolt** [comment]
Thanks. This has been on my todo list for a long while but I've yet to bite
to bullet and rearchitect GCC explorer to work with binary output instead
of the text output it currently uses.

**Comment by mattgodbolt** [comment]
Fixing this would also allow fixing #25

**Comment by mattgodbolt** [comment]
Please try again now. LTO is now supported, though do note that you'll need to write a `main()` that actually calls your test code else you'll end up with a `xor eax,eax` and nothing else.  Something like http://goo.gl/CMuwb1
