### ISSUE TITLE
Font / Layout issues 

### ISSUE THREAD

**Issue by samis** [mattgodbolt/gcc-explorer#90]
With the latest update, the code now has a much larger line spacing. This makes error-messages look huge, especially compared with the previous line-height. Is there any chance that this change could be reverted to improve how the code pane looks?

**Comment by mattgodbolt** [comment]
Absolutely; I had been testing on a laptop with the font size tweaked to be
smaller and this change was unintentional! Thanks for reporting the issue!

**Comment by mattgodbolt** [comment]
Fix is in the process of deploying (which takes my crappy autoscripts a few
minutes...) thanks again!

On Tue, Nov 24, 2015 at 9:34 AM, Matt Godbolt <matt@godbolt.org> wrote:

> Absolutely; I had been testing on a laptop with the font size tweaked to
> be smaller and this change was unintentional! Thanks for reporting the
> issue!
>
> On Tue, Nov 24, 2015 at 9:05 AM, Samuel Hodgkins <notifications@github.com>
> wrote:
>
>> With the latest update, the code now has a much larger line spacing. This
>> makes error-messages look huge, especially compared with the previous
>> line-height. Is there any chance that this change could be reverted to
>> improve how the code pane looks?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/mattgodbolt/gcc-explorer/issues/90>.
>>
>


-- 
Matt
