### ISSUE TITLE
Boost libraries

### ISSUE THREAD

**Issue by haneefmubarak** [mattgodbolt/gcc-explorer#96]
It would be rather nice to have the Boost libraries (a rather common set of C++ header-only libraries) included in the environment (to see what code the templates generate). I'll send in a PR on the `Dockerfile` for this one.

**Comment by mattgodbolt** [comment]
Thanks Haneef!

I used to include boost but the compile times got so long that GCC explorer
backed up when under load. It now runs on a much faster machine so I think
this is a great idea!

I look forward to the PR!
