### ISSUE TITLE
Have some way of storing per-compiler options

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/gcc-explorer#98]
From Marius Cetateanu:
"...cache the compiler flags for the different compilers used; I switched from one architecture to the other a couple of times and is tedious to re-type the flags..."

He's right, he had a snippet which had ARM and x86 and going between the 
- x86 "-msse4.2 -O2"
- ARM "-mfloat-abi=hard -mfpu=neon -O2"

options was very annoying.

That said; we need to preserve the common case of switching between compiler versions and keeping the same options.

**Comment by celavek** [comment]
From Matt Godbolt:

> I often keep the compiler options the same as I switch between different compilers, and re-typing the flags between compiler switches would be the inverse problem to the one you have. ... 
> Perhaps a button to make the options "sticky" per compiler?
> 
> I've also long thought the list of compilers is getting unmanageable; perhaps I need to break it down hierarchically (by architecture and then by compiler, then by version)...then perhaps I could make the options sticky by architecture.

I do not think a button is necessary. Breaking down hierarchically by architecture and then by compiler is a good idea and would help visually. What would work for me(do not know if feasible):

 - the first time I select a compiler version for a specific compiler under a specific architecture the flags field is empty; as I type the flags they are cached for that specific version

 - as I move to another version of the same compiler the flags are brought along; if I modify them then the modified version of the flags should be cached for this specific version, leaving the cache for the other version intact

 - if I change the compiler within the same architecture then the flags are reset and we start fresh for the new compiler, of course what has been previously cached for another compiler rests intact

 - if I change the architecture then the flags are reset and we start fresh

**Comment by shixiao** [comment]
Along the same line of thought, it would be nice to have presets for per-compiler options, e.g., in etc/config/c++.xxx.properties
````javascript
compiler.g5x.name=x86 gcc 5.x
compiler.g5x.exe=.../gcc-5.x
compiler.g5x.options=... # options for gcc 5.x

compiler.clang.name=clang
compiler.clang.exe=.../clang++
compiler.clang.options=... # options for clang
...

options=... # common options for all compilers
````

We can merge them in compile.prototype.compile before running the compiler.

Another compiler option issues I ran into was due to the included library paths, some options tend to run very long. Would you be opposed to multi-line property support?

**Comment by mattgodbolt** [comment]
I'm hoping the new UI fixes this by allowing you to bring up both compilers side-by-side and have their own options applied.

Please re-open if you disagree.
